name: Java CI with Gradle

on:
  push:
    paths:
      - "src/**"
      - ".github/**"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            16    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Display commid hash
        run: |
          echo Tweak My Client \commit-${GITHUB_SHA::7} \(Public Beta\)
      - name: Set commid hash in codes
        run: |
          sed -i "s/build.undefined/${GITHUB_SHA::7}/g" gradle.properties
          sed -i "s/build.undefined/${GITHUB_SHA::7} \(Public Beta\)/g" src/main/java/top/hendrixshen/TweakMyClient/Reference.java
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload assets to GitHub
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from java 1.8 on one OS
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/
