name: Publish Release
on:
  release:
     types:
       - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache gradle files
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Display build number
      run: echo Tweak My Client \#$GITHUB_RUN_NUMBER
    - name: Set build number in codes
      run: sed -i "s/build.undefined/build.$GITHUB_RUN_NUMBER/g" src/main/java/top/hendrixshen/TweakMyClient/Reference.java build.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload assets to GitHub
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/libs/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
