name: Sync to Gitee

on: [push]

jobs:
  sync:
    if: ${{ github.repository_owner == 'Hendrix-Shen' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync to Gitee
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:Hendrix-Shen/Tweak-My-Client.git
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
